name = "Shopping Party"
client_id = "54b981744d85a2889fc89dda61b854cf"
application_url = "https://harmonious-centaur-d0da33.netlify.app"
embedded = true

[access_scopes]
# Required scopes for the app
scopes = "read_products,write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://harmonious-centaur-d0da33.netlify.app/auth/callback",
  "https://harmonious-centaur-d0da33.netlify.app/auth"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[app_preferences]
url = "https://harmonious-centaur-d0da33.netlify.app/settings"